//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUXILIAR
    {
        public int idAuxiliar { get; set; }
        public int codigoAuxiliar { get; set; }
        public string nombreAuxiliar { get; set; }
        public string apellidoAuxiliar { get; set; }
        public int edadAuxiliar { get; set; }
        public int dniAuxiliar { get; set; }
        public int ciudad_id { get; set; }
        public int sexo_id { get; set; }
        public int profesion_id { get; set; }
        public System.DateTime fechaNacimientoAuxiliar { get; set; }
        public System.DateTime fechaRegistroAuxiliar { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public int estadoAuxiliar_id { get; set; }
        public string correoElectronicoAuxiliar { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ESTADOAUXILIAR ESTADOAUXILIAR { get; set; }
        public virtual PROFESION PROFESION { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
