//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTE()
        {
            this.GESTIONMATERIA = new HashSet<GESTIONMATERIA>();
            this.INSCRIPCIONESTUDIANTEMATERIA = new HashSet<INSCRIPCIONESTUDIANTEMATERIA>();
        }
    
        public int idEstudiante { get; set; }
        public int numeroLegajo { get; set; }
        public string nombreEstudiante { get; set; }
        public string apellidoEstudiante { get; set; }
        public int edadEstudiante { get; set; }
        public int dniEstudiante { get; set; }
        public int ciudad_id { get; set; }
        public int sexo_id { get; set; }
        public int estadoEstudiante_id { get; set; }
        public string correoElectronico { get; set; }
        public System.DateTime fechaNacimientoEstudiante { get; set; }
        public System.DateTime fechaRegistroEstudiante { get; set; }
        public int carrera_id { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ESTADOESTUDIANTE ESTADOESTUDIANTE { get; set; }
        public virtual SEXO SEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GESTIONMATERIA> GESTIONMATERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCIONESTUDIANTEMATERIA> INSCRIPCIONESTUDIANTEMATERIA { get; set; }
    }
}
