//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPCIONESTUDIANTEMATERIA
    {
        public int idInscripcionEstudianteMateria { get; set; }
        public int estudiante_id { get; set; }
        public int materia_id { get; set; }
        public System.DateTime fechaInscripcionEstudiante { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
