//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANESTUDIO
    {
        public int idPlanEstudio { get; set; }
        public int carrera_id { get; set; }
        public int ciclo_id { get; set; }
        public int materia_id { get; set; }
        public Nullable<int> correlativa { get; set; }
        public Nullable<System.DateTime> anioPlanEstudio { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual CICLO CICLO { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
