//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESOR()
        {
            this.GESTIONMATERIA = new HashSet<GESTIONMATERIA>();
            this.INSCRIPCIONPROFESOR = new HashSet<INSCRIPCIONPROFESOR>();
        }
    
        public int idProfesor { get; set; }
        public int codigoProfesor { get; set; }
        public string nombreProfesor { get; set; }
        public string apellidoProfesor { get; set; }
        public int edadProfesor { get; set; }
        public int dniProfesor { get; set; }
        public int ciudad_id { get; set; }
        public System.DateTime fechaNacimientoProfesor { get; set; }
        public string correoElectronicoProfesor { get; set; }
        public int profesion_id { get; set; }
        public int sexo_id { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public System.DateTime fechaRegistroProfesor { get; set; }
        public int estadoProfesor_id { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ESTADOPROFESOR ESTADOPROFESOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GESTIONMATERIA> GESTIONMATERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCIONPROFESOR> INSCRIPCIONPROFESOR { get; set; }
        public virtual PROFESION PROFESION { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
