//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoUsuario { get; set; }
        public int edadUsuario { get; set; }
        public int dniUsuario { get; set; }
        public int ciudad_id { get; set; }
        public System.DateTime fechaNacimientoUsuario { get; set; }
        public string emailUsuario { get; set; }
        public int sexo_id { get; set; }
        public string usuarioUsuario { get; set; }
        public string claveUsuario { get; set; }
        public System.DateTime fechaRegistroUsuario { get; set; }
        public int rol_id { get; set; }
        public Nullable<int> celularUsuario { get; set; }
        public int estadoUsuario_id { get; set; }
        public bool activo { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ESTADOUSUARIO ESTADOUSUARIO { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
